### ISSUE TITLE
Unexpected addition of commons-text-api test dependency on BOM upgrade

### ISSUE THREAD

**Issue by MarkEWaite** [jenkinsci/bom#2484] opened 2023-09-10 12:22 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Elastic axis plugin upgrade from plugin bill of materials from 2401.v7a_d68f8d0b_09 to 2423.vce598171d115
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Running Java 11, Java 17, or Java 21 on Linux

### Reproduction steps

1. Attempt to upgrade the plugin bill of materials from 2401.v7a_d68f8d0b_09 to 2423.vce598171d115
    * https://github.com/jenkinsci/elastic-axis-plugin/pull/309
    * https://github.com/jenkinsci/nodelabelparameter-plugin/pull/265
    * https://github.com/jenkinsci/testng-plugin-plugin/pull/244
2. Detect the InjectedTest failure because plugin-utils-api cannot load without commons-text-api and commons-lang3-api
3. Insert a test dependency on commons-text-api plugin and the InjectedTest passes

### Expected Results

I assumed that this bom upgrade would be like previous bom upgrades, with no changes beyond the update of the bom version number.  That was the behavior for many of the other plugins that I maintain, but not for the elastic axis plugin.

### Actual Results

I was surprised that a new test dependency was required in the elastic axis plugin for this bom upgrade when it has not been required in previous bom upgrades.

### Anything else?

I'd like to understand the difference between previous bom releases and the most recent bom release.  The most recent bom release upgraded the commons-text-api plugin but an earlier upgrade to that plugin was processed a month ago without requiring the addition of a new test dependency.

I'm also happy if the answer is "this is not a surprise" for others.

**Comment by basil** [comment] 2023-09-11 19:06
`checks-api` 2.0.1 contained a plugin parent POM upgrade that (erroneously) removed its dependencies on `commons-text-api` and `commons-lang3-api` from the flattened POM (but not `MANIFEST.MF`, so test-only breakage rather than a production issue). The change in behavior was apparently caused by mojohaus/flatten-maven-plugin#329, released in 1.4.0 and adapted in plugin parent POM 4.57 in March 2023 but apparently not by Dr Hafner until September 2023. `checks-api` has a nonstandard parent POM that includes the dependencies on `commons-text-api` and `commons-lang3-api`, which was working only by accident prior to mojohaus/flatten-maven-plugin#329 and does not work at all after mojohaus/flatten-maven-plugin#329 due to `plugin-pom`'s use of the default value for https://www.mojohaus.org/flatten-maven-plugin/flatten-mojo.html#flattenDependencyMode. It would be fair to characterize this usage as "unsupported." I recommend deleting the `commons-text-api` and `commons-lang3-api` dependencies from `analysis-pom` and inlining them into each consumer.

**Comment by jonesbusy** [comment] 2023-09-12 19:07
Seen also here https://github.com/jenkinsci/bitbucket-kubernetes-credentials-plugin/commit/42dcf84fc1ef7bad98afc3876d731cdb54929c6c

**Comment by basil** [comment] 2023-09-12 21:46
Since this is a problem with `jenkinsci/analysis-pom-plugin` and/or `jenkinsci/checks-api-plugin` rather than `jenkinsci/bom`, I am closing this ticket. BOM maintainers are encouraged to revert the problematic change to restore stability to BOM if necessary. Consumers of the BOM are asked to express themselves in https://github.com/jenkinsci/checks-api-plugin/issues/233 rather than in this ticket.

**Closed by basil** 2023-09-12 21:46 UTC
Labels: bug

**Comment by uhafner** [comment] 2023-09-19 11:51
> Since this is a problem with jenkinsci/analysis-pom-plugin and/or jenkinsci/checks-api-plugin rather than jenkinsci/bom, I am closing this ticket. BOM maintainers are encouraged to revert the problematic change to restore stability to BOM if necessary. Consumers of the BOM are asked to express themselves in https://github.com/jenkinsci/checks-api-plugin/issues/233 rather than in this ticket.

I think that I do not understand your conclusion, can you please elaborate. Defining dependencies in a parent pom is a key concept of maven. So if this concept does not work in our build chain I would assume that our build chain has a defect that needs to be fixed.

**Comment by basil** [comment] 2023-09-19 17:23
> I would assume that our build chain has a defect that needs to be fixed.

Not when you are the only one in the Jenkins plugin community who is doing this and when the Maven developers have explicitly changed this behavior (including adding a test for the new behavior). Your choices are to take this up with the Maven developers or to conform to the rest of the Jenkins plugin community by removing plugin-to-plugin dependencies from `analysis-pom`.
