### ISSUE TITLE
Use newer PCT

### ISSUE THREAD

**Issue by jglick** [jenkinsci/bom#657] opened 2021-09-27 15:40 UTC
Currently using an incremental deployment of https://github.com/jenkinsci/plugin-compat-tester/pull/276. Need to get that released, and also check whether https://github.com/jenkinsci/plugin-compat-tester/pull/299 reveals failures (supposedly something in `workflow-scm-step at least).

**Comment by jglick** [comment] 2021-11-16 18:13
Another issue noticed in CB runs using `aws-java-sdk` is that either `-Dset.changelist` or `-am -pl` is needed when building a JEP-229-enabled plugin which uses a reactor. The current `-f repo/submodule` build does not work for modules which depend on siblings because the sibling snapshot is not present in the local reactor. So activate `-am -pl` whenever

```bash
mvn -Dexpression=project.version -q -DforceStdout help:evaluate | fgrep -- -SNAPSHOT
```

perhaps.

**Comment by basil** [comment] 2022-04-21 18:21
This long-standing issue, caused by the introduction of an unmerged and unreleased upstream change in a non-draft PR in #213, is blocking fixes like https://github.com/jenkinsci/plugin-compat-tester/pull/353 from being deployed to this repository and disincentivizing the development of fixes for other issues like #821 and #895. I am asking that we set a target date for the resolution of this issue.

**Comment by jglick** [comment] 2022-04-21 19:15
Updated #659 to see what the current list of problems is, though I am more inclined to work on https://github.com/jenkinsci/maven-hpi-plugin/pull/66 than to sink much more effort into PCT which in its current form seems fatally flawed.

> blocking fixes like https://github.com/jenkinsci/plugin-compat-tester/pull/353 from being deployed to this repository

Well, not “blocking” but making them more awkward since you need to merge them into the list of running patches first.

**Comment by basil** [comment] 2022-04-21 21:24
> I am more inclined to work on jenkinsci/maven-hpi-plugin#66 than to sink much more effort into PCT

But even even jenkinsci/maven-hpi-plugin#66 requires a patch to PCT, which in turn requires this issue to be resolved in order for such a patch to be deployed to this repository.

> Well, not “blocking” but making them more awkward since you need to merge them into the list of running patches first.

And become the de facto maintainer of that list of running patches? No thanks.

**Comment by jglick** [comment] 2022-04-21 21:34
> even https://github.com/jenkinsci/maven-hpi-plugin/pull/66 requires a patch to PCT

Most likely it would mean that we would still use PCT but in a much simplified form that just handled checking out repos and running a single `mvn verify` with an option pointing to a WAR or other source of dependency versions, but without any of the crazy POM rewriting.

Anyway, yes, we need to get trunk PCT working here somehow. Still TBD whether `configuration-as-code/test-harness` is the only outstanding problem.

**Comment by basil** [comment] 2022-05-02 15:09
> Updated #659 to see what the current list of problems is

While that helps clarify the nature of this long-standing issue, caused by the introduction of an unmerged and unreleased upstream change in a non-draft PR in #213, updating #659 to see the current list of problems still does not resolve this issue.

**Comment by basil** [comment] 2022-07-25 16:21
Not sure why this was closed, but the issue remains present. This repository still uses an old PCT. Reopening.

**Comment by timja** [comment] 2022-07-25 16:34
GitHub comment detection was a bit keen I think

**Closed** 2022-07-27 20:15 UTC
Labels: bug
